### ISSUE TITLE
Guidance with 159 Restarting Error

### ISSUE THREAD

**Issue by CameronBrooks11** [themattman/mongodb-raspberrypi-docker#23]
Hi, I'm trying to get mongo working on my RPi4B+ running the the 64 bit raspbian OS. I have installed it according to the readme:

```
pi@feast-alpha:~/mongo-test $ docker images
REPOSITORY                                  TAG       IMAGE ID       CREATED         SIZE
mongodb-raspberrypi4-unofficial-r7.0.4      latest    f604e9e73746   16 months ago   468MB
```

this is my compose script im running:

```
services:
  mongo:
    image: mongodb-raspberrypi4-unofficial-r7.0.4:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    container_name: mongo-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - ./db:/data/db
```

but it just fails silently saying "Restarting 159" and logs are blank:

```
pi@feast-alpha:~/mongo-test $ docker compose ps
NAME         IMAGE                                           COMMAND                  SERVICE   CREATED         STATUS                          PORTS
mongo-test   mongodb-raspberrypi4-unofficial-r7.0.4:latest   "docker-entrypoint.s…"   mongo     6 seconds ago   Restarting (159) 1 second ago
pi@feast-alpha:~/mongo-test $ docker logs -f mongo-test
pi@feast-alpha:~/mongo-test $ docker logs mongo-test
```

and a similar deal just running it straight without compose:

```
pi@feast-alpha:~ $ docker run -it mongodb-raspberrypi4-unofficial-r7.0.4
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v8) and no specific platform was requested
pi@feast-alpha:~ $ docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS                       PORTS     NAMES
48b8e29b2647   mongodb-raspberrypi4-unofficial-r7.0.4   "docker-entrypoint.s…"   3 seconds ago   Exited (159) 2 seconds ago             unruffled_euler
pi@feast-alpha:~ $ docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                       PORTS     NAMES
48b8e29b2647   mongodb-raspberrypi4-unofficial-r7.0.4   "docker-entrypoint.s…"   10 seconds ago   Exited (159) 8 seconds ago             unruffled_euler
```

I'm relatively new to MongoDB and Docker so any guidance on where I might be going wrong would be much appreciated
