### ISSUE TITLE
Docker hub host

### ISSUE THREAD

**Issue by andreclerigo** [themattman/mongodb-raspberrypi-docker#4]
Would be a great idea to host these on docker hub so people can pull images in a docker-compose.yml

**Comment by rshillington** [comment]
Or even better: It's right there [on the README](https://github.com/themattman/mongodb-raspberrypi-docker/blob/main/README.md#custom-build-steps-slower-more-control)

build the image yourself, and then push to a repository of your choosing.
Thinking about it some more, I'm not sure that docker hub would be the best place (unless you keep it private)

**Comment by isaric** [comment]
Why not use Github Actions and push to ghcr.io? If it's a public repo, everyone can pull from it.

**Comment by tk-nguyen** [comment]
For anyone passing through here, `docker build` and `docker buildx build` supports [contexts](https://docs.docker.com/build/concepts/context/). We can use [Git repositories](https://docs.docker.com/build/concepts/context/#git-repositories) as contexts, so you don't have to manually do anything.

A sample `compose.yaml` file like so:

```yaml
services:
  mongodb:
    build: https://github.com/themattman/mongodb-raspberrypi-docker.git#:7.0.8
```

or

```yaml
services:
  mongodb:
    build:
      context: https://github.com/themattman/mongodb-raspberrypi-docker.git#:7.0.8
```

should automatically clone the repo, and use the `7.0.8` directory from the git repo root as build context. This is described in https://docs.docker.com/reference/compose-file/build/#attributes.

More information about the Git context syntax is at https://docs.docker.com/build/concepts/context/#git-repositories.

Good luck!
